export enum Operator {
  is_null = 'is_null',
  not_null = 'not_null',
  str_eq = 'str_eq',
  n_str_eq = 'n_str_eq',
  str_in = 'str_in',
  n_str_in = 'n_str_in',
  regex = 'regex',
  num_eq = 'num_eq',
  n_num_eq = 'n_num_eq',
  gt = 'gt',
  lt = 'lt',
  gte = 'gte',
  lte = 'lte',
  num_between = 'num_between',
  date_eq = 'date_eq',
  n_date_eq = 'n_date_eq',
  before = 'before',
  after = 'after',
  date_between = 'date_between',
}
